// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOhvlOZQT8mOsHXayFcvOig3jBC2I6n4',
    appId: '1:835715365075:web:02db59e305fe1a9bc1bc26',
    messagingSenderId: '835715365075',
    projectId: 'todo-app-32142',
    authDomain: 'todo-app-32142.firebaseapp.com',
    storageBucket: 'todo-app-32142.appspot.com',
    measurementId: 'G-6PK4TD0BCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrc7gvO8bRG1-n8MVm33-yN6xocMajJUg',
    appId: '1:835715365075:android:8b527b306686238ec1bc26',
    messagingSenderId: '835715365075',
    projectId: 'todo-app-32142',
    storageBucket: 'todo-app-32142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqhGt2B7QGS7KrsVCvjluV1lo2m7_dW9M',
    appId: '1:835715365075:ios:295548264181a1f1c1bc26',
    messagingSenderId: '835715365075',
    projectId: 'todo-app-32142',
    storageBucket: 'todo-app-32142.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqhGt2B7QGS7KrsVCvjluV1lo2m7_dW9M',
    appId: '1:835715365075:ios:fcd61f568f1c90d5c1bc26',
    messagingSenderId: '835715365075',
    projectId: 'todo-app-32142',
    storageBucket: 'todo-app-32142.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
